### ISSUE TITLE
qs

### ISSUE THREAD

**Issue by RenShengJ** [gradywright/cfpu#1]
You will need to download these libraries and compile the MEX files according to the instructions in the help text of the C++ mex files.
Tried several times but failed,,Is there a more detailed operation process to text of the C++ mex files?
![image](https://user-images.githubusercontent.com/52486818/204090873-3435737a-a26a-473a-86b9-461ee1ec490e.png)

**Comment by gradywright** [comment]
I have only tried compiling the libraries on MacOs and Linux and have not run into any problems.  You may want to search the [VCG](https://github.com/cnr-isti-vclab/vcglib/) documentation for help on windows compilation.
