### ISSUE TITLE
How can Patches be obtained?

### ISSUE THREAD

**Issue by harmony96** [gradywright/cfpu#3]
According the description, CFPU produces an implicit surface from a point cloud consisting of points and normals. 
However,your matlab code of 'cfpurecon' requires patches.
Would you let me know how the patches can be obtained?

**Comment by gradywright** [comment]
The last example in [cfpu_ex.m](https://github.com/gradywright/cfpu/blob/4f5dd85b8d8b434e547315b003fd79b19cc61362/code/cfpu_ex.m#L286) shows how to do this.
